version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres:13-alpine3.13
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/
    volumes:
      - .:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data/
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - '${PGADMIN_PORT}:80'
    networks:
      - postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

networks:
  postgres:
    driver: bridge

volumes:
  pgadmin:
